// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: google/api/servicecontrol/v1/service_controller.proto

#include "google/api/servicecontrol/v1/service_controller.pb.h"
#include "google/api/servicecontrol/v1/service_controller.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace google {
namespace api {
namespace servicecontrol {
namespace v1 {

static const char* ServiceController_method_names[] = {
  "/google.api.servicecontrol.v1.ServiceController/Check",
  "/google.api.servicecontrol.v1.ServiceController/Report",
};

std::unique_ptr< ServiceController::Stub> ServiceController::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ServiceController::Stub> stub(new ServiceController::Stub(channel));
  return stub;
}

ServiceController::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Check_(ServiceController_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Report_(ServiceController_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ServiceController::Stub::Check(::grpc::ClientContext* context, const ::google::api::servicecontrol::v1::CheckRequest& request, ::google::api::servicecontrol::v1::CheckResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Check_, context, request, response);
}

void ServiceController::Stub::experimental_async::Check(::grpc::ClientContext* context, const ::google::api::servicecontrol::v1::CheckRequest* request, ::google::api::servicecontrol::v1::CheckResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Check_, context, request, response, std::move(f));
}

void ServiceController::Stub::experimental_async::Check(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::google::api::servicecontrol::v1::CheckResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Check_, context, request, response, std::move(f));
}

void ServiceController::Stub::experimental_async::Check(::grpc::ClientContext* context, const ::google::api::servicecontrol::v1::CheckRequest* request, ::google::api::servicecontrol::v1::CheckResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Check_, context, request, response, reactor);
}

void ServiceController::Stub::experimental_async::Check(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::google::api::servicecontrol::v1::CheckResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Check_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::api::servicecontrol::v1::CheckResponse>* ServiceController::Stub::AsyncCheckRaw(::grpc::ClientContext* context, const ::google::api::servicecontrol::v1::CheckRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::google::api::servicecontrol::v1::CheckResponse>::Create(channel_.get(), cq, rpcmethod_Check_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::google::api::servicecontrol::v1::CheckResponse>* ServiceController::Stub::PrepareAsyncCheckRaw(::grpc::ClientContext* context, const ::google::api::servicecontrol::v1::CheckRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::google::api::servicecontrol::v1::CheckResponse>::Create(channel_.get(), cq, rpcmethod_Check_, context, request, false);
}

::grpc::Status ServiceController::Stub::Report(::grpc::ClientContext* context, const ::google::api::servicecontrol::v1::ReportRequest& request, ::google::api::servicecontrol::v1::ReportResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Report_, context, request, response);
}

void ServiceController::Stub::experimental_async::Report(::grpc::ClientContext* context, const ::google::api::servicecontrol::v1::ReportRequest* request, ::google::api::servicecontrol::v1::ReportResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Report_, context, request, response, std::move(f));
}

void ServiceController::Stub::experimental_async::Report(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::google::api::servicecontrol::v1::ReportResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Report_, context, request, response, std::move(f));
}

void ServiceController::Stub::experimental_async::Report(::grpc::ClientContext* context, const ::google::api::servicecontrol::v1::ReportRequest* request, ::google::api::servicecontrol::v1::ReportResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Report_, context, request, response, reactor);
}

void ServiceController::Stub::experimental_async::Report(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::google::api::servicecontrol::v1::ReportResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Report_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::api::servicecontrol::v1::ReportResponse>* ServiceController::Stub::AsyncReportRaw(::grpc::ClientContext* context, const ::google::api::servicecontrol::v1::ReportRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::google::api::servicecontrol::v1::ReportResponse>::Create(channel_.get(), cq, rpcmethod_Report_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::google::api::servicecontrol::v1::ReportResponse>* ServiceController::Stub::PrepareAsyncReportRaw(::grpc::ClientContext* context, const ::google::api::servicecontrol::v1::ReportRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::google::api::servicecontrol::v1::ReportResponse>::Create(channel_.get(), cq, rpcmethod_Report_, context, request, false);
}

ServiceController::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServiceController_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServiceController::Service, ::google::api::servicecontrol::v1::CheckRequest, ::google::api::servicecontrol::v1::CheckResponse>(
          std::mem_fn(&ServiceController::Service::Check), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServiceController_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServiceController::Service, ::google::api::servicecontrol::v1::ReportRequest, ::google::api::servicecontrol::v1::ReportResponse>(
          std::mem_fn(&ServiceController::Service::Report), this)));
}

ServiceController::Service::~Service() {
}

::grpc::Status ServiceController::Service::Check(::grpc::ServerContext* context, const ::google::api::servicecontrol::v1::CheckRequest* request, ::google::api::servicecontrol::v1::CheckResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ServiceController::Service::Report(::grpc::ServerContext* context, const ::google::api::servicecontrol::v1::ReportRequest* request, ::google::api::servicecontrol::v1::ReportResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace google
}  // namespace api
}  // namespace servicecontrol
}  // namespace v1

