/*! AWAITING HUGO JSON CONVERSION TOOL */
#define BOOST_OUTCOME_VERSION_MAJOR    2
/*! AWAITING HUGO JSON CONVERSION TOOL */
#define BOOST_OUTCOME_VERSION_MINOR    0
/*! AWAITING HUGO JSON CONVERSION TOOL */
#define BOOST_OUTCOME_VERSION_PATCH    0 
/*! AWAITING HUGO JSON CONVERSION TOOL */
#define BOOST_OUTCOME_VERSION_REVISION 0  // Revision version for cmake and DLL version stamping

/*! AWAITING HUGO JSON CONVERSION TOOL */
#ifndef BOOST_OUTCOME_DISABLE_ABI_PERMUTATION
#define BOOST_OUTCOME_UNSTABLE_VERSION
#endif
