//
// Please put here the includes for other libcode components
//
#pragma once
#include "object.hpp"

//
// ClassId's declarations
//
namespace openEdr {

CMD_DECLARE_LIBRARY_CLSID(CLSID_Log4CPlusSink, 0xE18D3126);
CMD_DECLARE_LIBRARY_CLSID(CLSID_MemoryStream, 0x8AD7D6FC);
CMD_DECLARE_LIBRARY_CLSID(CLSID_RawReadableStreamCache, 0x8C5CE6B4);
CMD_DECLARE_LIBRARY_CLSID(CLSID_ReadableStreamCache, 0x92A54AD4);
CMD_DECLARE_LIBRARY_CLSID(CLSID_RawReadableStreamConverter, 0x80A21656);
CMD_DECLARE_LIBRARY_CLSID(CLSID_PartOfStream, 0x89F63C68);
CMD_DECLARE_LIBRARY_CLSID(CLSID_File, 0xCEFC4454);
CMD_DECLARE_LIBRARY_CLSID(CLSID_FileWin, 0xCABC320F);
CMD_DECLARE_LIBRARY_CLSID(CLSID_VariantCtxCmd, 0x3C365C39);
CMD_DECLARE_LIBRARY_CLSID(CLSID_VariantCmd, 0x9FD7EEDA);
CMD_DECLARE_LIBRARY_CLSID(CLSID_CallCtxCmd, 0x59D2EF6E);
CMD_DECLARE_LIBRARY_CLSID(CLSID_ConditionalCtxCmd, 0x9D3DE14A);
CMD_DECLARE_LIBRARY_CLSID(CLSID_ForEachCtxCmd, 0x689C6951);
CMD_DECLARE_LIBRARY_CLSID(CLSID_MakeDictionaryCtxCmd, 0xA503B509);
CMD_DECLARE_LIBRARY_CLSID(CLSID_MakeSequenceCtxCmd, 0x9ADE59BC);
CMD_DECLARE_LIBRARY_CLSID(CLSID_CachedValueCtxCmd, 0x69895E6D);
CMD_DECLARE_LIBRARY_CLSID(CLSID_Command, 0xACE892B6);
CMD_DECLARE_LIBRARY_CLSID(CLSID_ScenarioManager, 0xB15D1291);
CMD_DECLARE_LIBRARY_CLSID(CLSID_Scenario, 0x61A30254);
CMD_DECLARE_LIBRARY_CLSID(CLSID_CommandDataReceiver, 0xEF918300);
CMD_DECLARE_LIBRARY_CLSID(CLSID_ServiceManager, 0xE3C898E1);
CMD_DECLARE_LIBRARY_CLSID(CLSID_Base64Encoder, 0xBD9D4986);
CMD_DECLARE_LIBRARY_CLSID(CLSID_Base64Decoder, 0x6B5AC37A);
CMD_DECLARE_LIBRARY_CLSID(CLSID_StringReadableStream, 0xE79186C8);
CMD_DECLARE_LIBRARY_CLSID(CLSID_DictionaryStreamView, 0x54AFB9F0);
CMD_DECLARE_LIBRARY_CLSID(CLSID_Console, 0xC5CC9453);
CMD_DECLARE_LIBRARY_CLSID(CLSID_JsonRpcClient, 0x694C9C8E);
CMD_DECLARE_LIBRARY_CLSID(CLSID_JsonRpcServer, 0xDAA32B15);
CMD_DECLARE_LIBRARY_CLSID(CLSID_Queue, 0x37C541FD);
CMD_DECLARE_LIBRARY_CLSID(CLSID_DataGenerator, 0xB769174E);
CMD_DECLARE_LIBRARY_CLSID(CLSID_ChangeMe, 0xFFFFFFFF);
CMD_DECLARE_LIBRARY_CLSID(CLSID_QueueManager, 0x9E88430D);
CMD_DECLARE_LIBRARY_CLSID(CLSID_QueueProxy, 0xDE854411);
CMD_DECLARE_LIBRARY_CLSID(CLSID_DictionaryMixer, 0xAB3C615E);
CMD_DECLARE_LIBRARY_CLSID(CLSID_StringMatcher, 0x40938389);
CMD_DECLARE_LIBRARY_CLSID(CLSID_NullStream, 0x2CFF4596);
CMD_DECLARE_LIBRARY_CLSID(CLSID_RandomDataGenerator, 0xD3A70691);
CMD_DECLARE_LIBRARY_CLSID(CLSID_FsDataStorage, 0xDA024E57);
CMD_DECLARE_LIBRARY_CLSID(CLSID_AesEncoder, 0xE6DA4FEE);
CMD_DECLARE_LIBRARY_CLSID(CLSID_AesDecoder, 0x1ED3E4B9);
CMD_DECLARE_LIBRARY_CLSID(CLSID_StreamSerializer, 0x059432FF);
CMD_DECLARE_LIBRARY_CLSID(CLSID_StreamDeserializer, 0x8397E8A0);
CMD_DECLARE_LIBRARY_CLSID(CLSID_StringCache, 0x404B416C);
CMD_DECLARE_LIBRARY_CLSID(CLSID_LocalEventsLogFile, 0xCEFC4455);


} // namespace openEdr

